[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "9vKyKVGXNgJyygnHcAg8hKLZZnHEteV83b6e56qScyTc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ineshreddy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
